// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcAlDC8V0sfKJzldcxsLT_C52uJ-hPVH8',
    appId: '1:524386604189:web:63ec5410c43d742a317074',
    messagingSenderId: '524386604189',
    projectId: 'my-flutter-firestore-dd',
    authDomain: 'my-flutter-firestore-dd.firebaseapp.com',
    storageBucket: 'my-flutter-firestore-dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqqnvO8VycDQcy3kShrqB76ndXRSJAjkM',
    appId: '1:524386604189:android:168f5a337665f3e5317074',
    messagingSenderId: '524386604189',
    projectId: 'my-flutter-firestore-dd',
    storageBucket: 'my-flutter-firestore-dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_G6c0cfdwlX0KSQZcyxVVkVWr9TcLX60',
    appId: '1:524386604189:ios:5b8422ab9ab4b3e0317074',
    messagingSenderId: '524386604189',
    projectId: 'my-flutter-firestore-dd',
    storageBucket: 'my-flutter-firestore-dd.appspot.com',
    iosClientId: '524386604189-m25dabmea225os0g713b5vhfov5pkv11.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_G6c0cfdwlX0KSQZcyxVVkVWr9TcLX60',
    appId: '1:524386604189:ios:5b8422ab9ab4b3e0317074',
    messagingSenderId: '524386604189',
    projectId: 'my-flutter-firestore-dd',
    storageBucket: 'my-flutter-firestore-dd.appspot.com',
    iosClientId: '524386604189-m25dabmea225os0g713b5vhfov5pkv11.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameApp',
  );
}
